name: Black
on: [ push, pull_request ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: black
        uses: psf/black@21.7b0