name: Flake8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x (latest)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Flake8
        run: |
          python -m pip install flake8
          flake8