name: Run isort
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: isort/isort-action@master
        # with:
            # requirementsFiles: "requirements.txt requirements-dev.txt"